// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfPgIyJRK9_Cu8awi5jeTQ4NXu3nwrYpw',
    appId: '1:1002872122808:web:b5baa8efc3fcc0fbad334d',
    messagingSenderId: '1002872122808',
    projectId: 'spenza-recipe-app',
    authDomain: 'spenza-recipe-app.firebaseapp.com',
    storageBucket: 'spenza-recipe-app.appspot.com',
    measurementId: 'G-N5196MJMJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg-xLLjwqZFX23wtR7JcFhiDz5cD0c4m4',
    appId: '1:1002872122808:android:928eac8a9127704aad334d',
    messagingSenderId: '1002872122808',
    projectId: 'spenza-recipe-app',
    storageBucket: 'spenza-recipe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkEBnl4zVTDAtas7mv91rfO-Hmfy9I5tw',
    appId: '1:1002872122808:ios:d16d47c80b6f9948ad334d',
    messagingSenderId: '1002872122808',
    projectId: 'spenza-recipe-app',
    storageBucket: 'spenza-recipe-app.appspot.com',
    androidClientId: '1002872122808-jkemf3uf2adoh2npiql3q60pevm7es4h.apps.googleusercontent.com',
    iosClientId: '1002872122808-mqe9799cr2l20k3l8oc8g7u1rcntg784.apps.googleusercontent.com',
    iosBundleId: 'com.pocketdevs.spenza',
  );
}
